config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("menus/", include("menus.urls", namespace="menus")),
    path("users/", include("users.urls", namespace="users")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path("purchases/", include("purchases.urls", namespace="purchases")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path(
        "go/<int:menu_owner_pk>/<int:asking_user_pk>", views.go_conversation, name="go"
    ),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
    path("", views.ConversationView.as_view(), name="all-conversations"),
]

core/urls.py
from django.urls import path
from menus import views as menu_views


app_name = "core"

urlpatterns = [
    path("", menu_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("", views.ListDetailView.as_view(), name="list-detail"),
    path("add/<int:pk>", views.addToMyList, name="add-to-list"),
    path("delete/<int:pk>", views.deleteItem, name="delete-item"),
]

menus/urls.py
from django.urls import path
from . import views


app_name = "menus"

urlpatterns = [
    path("<int:pk>/", views.MenuDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("update-menu/<int:pk>", views.UpdateMenuView.as_view(), name="update-menu"),
    path("<int:pk>/photos/", views.MenuPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:menu_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path(
        "<int:menu_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path("create/<int:business_pk>", views.CreateMenuView.as_view(), name="create"),
]

purchases/urls.py
from django.urls import path
from . import views

app_name = "purchases"

urlpatterns = [
    path("history/", views.HistoryView.as_view(), name="history"),
    path("order/<int:pk>", views.create, name="order"),
]

menus/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class FoodType(AbstractItem):

    """ FoodType Model Definition """

    class Meta:
        verbose_name = "Food Type"


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=100)
    file = models.ImageField(upload_to="food_photos")
    menu = models.ForeignKey(
        "Menu", related_name="photos", on_delete=models.CASCADE, blank=True
    )

    def __str__(self):
        return self.caption


class Menu(core_models.TimeStampedModel):

    """ Menu Model Definition """

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(
        max_digits=5, decimal_places=2, validators=[MinValueValidator(0)],
    )
    stock = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(500)],
    )
    business = models.ForeignKey(
        "businesses.Business", related_name="menus", on_delete=models.CASCADE, null=True
    )
    food_type = models.ManyToManyField("FoodType", related_name="menus", blank=True)

    def __str__(self):
        return self.name

    def in_progress(self):
        today = timezone.now().date()
        return self.stock > 0 and self.created.date() == today

    in_progress.boolean = True

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_absolute_url(self):
        return reverse("menus:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

menus/forms.py
from django import forms
from . import models


class SearchForm(forms.Form):

    STATE_ACT = "ACT"
    STATE_NSW = "NSW"
    STATE_NT = "NT"
    STATE_QLD = "QLD"
    STATE_SA = "SA"
    STATE_TAS = "TAS"
    STATE_VIC = "VIC"
    STATE_WA = "WA"
    STATE_FIRST = "None"
    STATE_CHOICES = (
        (STATE_FIRST, "Anywhere"),
        (STATE_ACT, "Australian Capital Territory"),
        (STATE_NSW, "New South Wales"),
        (STATE_NT, "Northern Territory"),
        (STATE_QLD, "Queensland"),
        (STATE_SA, "South Australia"),
        (STATE_TAS, "Tasmania"),
        (STATE_VIC, "Victoria"),
        (STATE_WA, "Western Australia"),
    )

    state = forms.ChoiceField(choices=STATE_CHOICES)
    food_type = forms.ModelChoiceField(
        required=False,
        empty_label="Any kind",
        queryset=models.FoodType.objects.all(),
        label="Food Type",
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        menu = models.Menu.objects.get(pk=pk)
        photo.menu = menu
        photo.save()


class CreateMenuForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = (
            "name",
            "description",
            "price",
            "stock",
            "food_type",
        )

    def save(self, *args, **kwargs):
        menu = super().save(commit=False)
        return menu

menus/views.py
from django.http import Http404
from django.views.generic import View, ListView, DetailView, UpdateView, FormView
from django.shortcuts import render, reverse, redirect
from django.core.paginator import Paginator
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from users import mixins as user_mixins
from . import models, forms
from businesses import models as business_model
from slider import models as slider_models


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Menu
    paginate_by = 5
    # paginate_orphans = 3
    context_object_name = "menus"

    def get_queryset(self):
        if self.request.user.is_anonymous:
            return models.Menu.objects.all()

        return models.Menu.objects.filter(business__state=self.request.user.state)

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context["images"] = slider_models.Slider.objects.all()
        return context


class MenuDetail(DetailView):

    """ MenuDetail Definition """

    model = models.Menu


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):
        state = request.GET.get("state")

        if state:
            form = forms.SearchForm(request.GET)

            if form.is_valid():
                state = form.cleaned_data.get("state")
                food_type = form.cleaned_data.get("food_type")
                filter_args = {}

                if state != "None":
                    filter_args["business__state"] = state

                if food_type is not None:
                    filter_args["food_type"] = food_type

                qs = models.Menu.objects.filter(**filter_args).order_by("-created")
                paginator = Paginator(qs, 5, orphans=2)
                page = request.GET.get("page", 1)
                menus = paginator.get_page(page)

                return render(
                    request, "menus/search.html", {"form": form, "menus": menus}
                )

        else:
            form = forms.SearchForm()

        return render(request, "menus/search.html", {"form": form})


class UpdateMenuView(UpdateView):

    """ UpdateMenuView Definition """

    model = models.Menu
    template_name = "menus/update-menu.html"
    fields = ("name", "description", "price", "stock", "food_type")
    success_message = "Profile Updated"

    def get_object(self, queryset=None):
        menu = super().get_object(queryset=queryset)
        if menu.business.owner.pk != self.request.user.pk:
            raise Http404()
        return menu

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs = {"placeholder": "Name"}
        form.fields["description"].widget.attrs = {"placeholder": "Description"}
        form.fields["price"].widget.attrs = {"placeholder": "price"}
        form.fields["stock"].widget.attrs = {"placeholder": "stock"}
        form.fields["food_type"].widget.attrs = {"placeholder": "food_type"}
        return form


class MenuPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    """ MenuPhotosView Definition """

    model = models.Menu
    template_name = "menus/menu_photos.html"

    def get_object(self, queryset=None):
        menu = super().get_object(queryset=queryset)
        if menu.business.owner.pk != self.request.user.pk:
            raise Http404()
        return menu


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    """ AddPhotoView Definition """

    template_name = "menus/photo_create.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("menus:photos", kwargs={"pk": pk}))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    """ EditPhotoView Definition """

    model = models.Photo
    template_name = "menus/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = ("caption",)

    def get_success_url(self):
        menu_pk = self.kwargs.get("menu_pk")
        return reverse("menus:photos", kwargs={"pk": menu_pk})


@login_required
def delete_photo(request, menu_pk, photo_pk):
    user = request.user
    try:
        menu = models.Menu.objects.get(pk=menu_pk)
        if menu.business.owner.pk != user.pk:
            messages.error(request, "Cant delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("menus:photos", kwargs={"pk": menu_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class CreateMenuView(user_mixins.LoggedInOnlyView, FormView):

    """ CreateMenuViews Definition """

    form_class = forms.CreateMenuForm
    template_name = "menus/menu_create.html"

    def form_valid(self, form):
        menu = form.save()
        business_pk = self.kwargs.get("business_pk")
        menu.business = business_model.Business.objects.get(pk=business_pk)
        menu.save()
        form.save_m2m()
        messages.success(self.request, "Menu Uploaded")
        return redirect(reverse("menus:detail", kwargs={"pk": menu.pk}))

templates/menus/menu_create.html
{% extends "base.html" %}

{% block page_title %}
Create Menu
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="signup-form m-t-10">
    {% include 'mixins/menu/menu_form.html' with form=form cta="Create business" %}
</div>
{% endblock content %}

templates/menus/menu_detail.html
{% extends 'base.html' %}


{% block page_title %}
{{menu.name}}
{% endblock page_title %}


{% block content %}

<div class="menu-detail">
    <p><img src="{{menu.first_photo}}" style="width: 300px;"></p>
    <p><b>Name: </b>{{menu.name}}</p>
    <p><b>Description: </b>{{menu.description}}</p>
    <p><b>Price: </b>{{menu.price}}</p>
    <p><b>Offered by: </b><a href="{{menu.business.get_absolute_url}}">{{menu.business}}</a> /
        {{menu.business.total_rating}}
    </p>
    <p>
        <b>Owner: </b><a href="{{menu.business.owner.get_absolute_url}}">{{menu.business.owner}}</a>

        {% if menu.business.owner.pk != user.pk %}
        {% if user.is_anonymous != True %}
        <a href="{% url 'conversations:go' menu.business.owner.pk user.pk %}">(Send a message)</a>
        {% endif %}
        {% endif %}

    </p>
    <p><b>Available State: </b>{{menu.business.state}}</p>
    <p><b>Food Type: </b>
        {% for f in menu.food_type.all %}
        {% if forloop.last %}
        {{ f }}
        {% else %}
        {{ f }},
        {% endif %}
        {% endfor %}
    </p>
    <p><b>Stock: </b>
        {{menu.stock}}
    </p>

    {% if user.pk == menu.business.owner.pk %}
    <p><a href="{% url 'menus:update-menu' menu.pk %}">Update menu</a></p>
    {% else %}
    <p><a href="{% url 'lists:add-to-list' menu.pk %}"><button>Add to my favorite list</button></a></p>
    <p><a href="{% url 'purchases:order' menu.pk %}"><button>Purchase</button></a></p>
    {% endif %}

</div>

{% endblock content %}

templates/menus/menu_list.html
{% extends 'base.html' %}


{% block page_title %}
Home
{% endblock page_title %}


{% block content %}

<div class="flex flex-wrap m-h-center w-95per">
    {% for menu in menus %}
    {% include 'mixins/menu_card.html' with menu=menu %}
    {% endfor %}
</div>

<div class="p-l-40 p-r-40">
    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">
        PRV
    </a>
    {% endif %}

    <span>
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next  %}
    <a href="?page={{page_obj.next_page_number}}">
        NEXT
    </a>
    {% endif %}
</div>

{% endblock content %}

templates/menus/menu_photos.html
{% extends "base.html" %}

{% block page_title %}
{{menu.name}}'s Photo
{% endblock page_title %}

{% block content %}

<div>
    <div class="text-align-center">
        <a href="{% url 'menus:add-photo' menu.pk %}">
            <button class="m-t-10 m-b-10 photo-btn">
                Upload Photo
            </button>
        </a>
    </div>

    {% for photo in menu.photos.all  %}
    <div>
        <div class="signup-form">
            <img src="{{photo.file.url}}" style="width: 100%;">
            <span><b>Caption: </b>{{photo.caption}}</span>
        </div>
        <div class="text-align-center">
            <a href="{% url 'menus:edit-photo' menu.pk photo.pk %}">
                <button class="m-t-10 m-b-10 photo-btn">
                    Edit
                </button>
            </a>
        </div>
        <div class="text-align-center">
            <a href="{% url 'menus:delete-photo' menu.pk photo.pk %}">
                <button class="m-t-10 m-b-10 photo-btn">
                    Delete
                </button>
            </a>
        </div>
    </div>
    {% endfor %}

    <div class="text-align-center">
        <a href="{% url 'menus:update-menu' menu.pk %}" class="photo-button">
            <button class="m-t-10 m-b-10 photo-btn">
                Back to edit room
            </button>
        </a>
    </div>
</div>
{% endblock content %}

templates/menus/photo_create.html
{% extends "base.html" %}

{% block page_title %}
Upload photo
{% endblock page_title %}

{% block content %}

<div class="signup-form">

    {% include 'mixins/menu/menu_form.html' with form=form cta="Upload photo" %}

</div>
{% endblock content %}

templates/menus/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
Update photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="signup-form m-t-10">
    {% include 'mixins/menu/menu_form.html' with form=form cta="Update photo" %}
</div>
{% endblock content %}

templates/menus/search.html
{% extends "base.html" %}

{% block page_title %}
Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<h2>Search</h2>

<form method="get" action="{% url "menus:search" %}" class="signup-form">
    {{form.as_p}}
    <button>Search</button>
</form>

<h3>Results</h3>

{% for menu in menus %}
<div class="flex">
    {% include 'mixins/menu_card.html' with menu=menu %}
</div>
<!-- <h3><a href="{% url 'menus:detail' menu.pk %}">{{menu.name}}</a></h3> -->
{% endfor %}


{% endblock content %}

templates/menus/update-menu.html
{% extends "base.html" %}

{% block page_title %}
Update Menu
{% endblock page_title %}

{% block content %}

<div class="signup-form m-t-10 m-b-10">
    {% include 'mixins/auth/auth_form.html' with form=form cta="Update menu" %}
    <p><a href="{% url 'menus:photos' menu.pk %}">Edit photo</a></p>
</div>
{% endblock content %}