config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("menus/", include("menus.urls", namespace="menus")),
    path("users/", include("users.urls", namespace="users")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path("purchases/", include("purchases.urls", namespace="purchases")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from menus import views as menu_views


app_name = "core"

urlpatterns = [
    path("", menu_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("", views.ListDetailView.as_view(), name="list-detail"),
    path("add/<int:pk>", views.addToMyList, name="add-to-list"),
    path("delete/<int:pk>", views.deleteItem, name="delete-item"),
]

menus/urls.py
from django.urls import path
from . import views


app_name = "menus"

urlpatterns = [
    path("<int:pk>/", views.MenuDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("update-menu/<int:pk>", views.UpdateMenuView.as_view(), name="update-menu"),
    path("<int:pk>/photos/", views.MenuPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:menu_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path(
        "<int:menu_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path("create/<int:business_pk>", views.CreateMenuView.as_view(), name="create"),
]

lists/models.py
from django.db import models
from core import models as core_models


class List(core_models.TimeStampedModel):
    user = models.ForeignKey(
        "users.User", related_name="lists", on_delete=models.CASCADE
    )
    # menu = models.ManyToManyField("menus.Menu", blank=True)
    menu = models.ForeignKey(
        "menus.Menu",
        related_name="lists",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def __str__(self):
        date = self.created.date()
        format_date = date.strftime("%Y/%m/%d")
        return f"{format_date} / {self.user}"

    class Meta:
        ordering = ("-created",)

lists/views.py
from django.views.generic import ListView
from django.shortcuts import redirect, reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . import models
from menus import models as menu_models
from users import mixins


class ListDetailView(ListView, mixins.LoggedInOnlyView):

    """ HistoryView Definition """

    model = models.List
    paginate_by = 10
    paginate_orphans = 3
    context_object_name = "lists"

    def get_queryset(self):
        return models.List.objects.filter(user=self.request.user)


class CreateError(Exception):
    pass


@login_required
def addToMyList(request, pk):
    try:
        models.List.objects.get(user=request.user, menu=pk)
        raise CreateError()
    except (CreateError):
        messages.error(request, "You already have this menu in your list")
        return redirect(reverse("menus:detail", kwargs={"pk": pk}))
    except models.List.DoesNotExist:
        menu = menu_models.Menu.objects.get(pk=pk)
        models.List.objects.create(
            user=request.user, menu=menu,
        )
        return redirect(reverse("lists:list-detail"))


@login_required
def deleteItem(request, pk):
    models.List.objects.filter(pk=pk).delete()
    return redirect(reverse("lists:list-detail"))

templates/lists/list_list.html
{% extends 'base.html' %}

{% block page_title %}
Favorite List
{% endblock page_title %}

{% block content %}

{% for list in lists %}
<div class="signup-form m-t-10">
    <p><b>Menu: </b><a href="{% url 'menus:detail' list.menu.pk %}">{{ list.menu }}</a></p>
    <p>
        <b>Food Type: </b>
        {% for f in list.menu.food_type.all %}
        {% if forloop.last %}
        {{f}}
        {% else %}
        {{f}},
        {% endif %}
        {% endfor %}
    </p>
    <p><b>Price: </b>{{ list.menu.price }}</p>
    <a href="{% url 'lists:delete-item' list.pk %}"><button>Delete this menu</button></a>
</div>
{% endfor %}

<div>
    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">
        PRV
    </a>
    {% endif %}

    <span>
        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next  %}
    <a href="?page={{page_obj.next_page_number}}">
        NEXT
    </a>
    {% endif %}
</div>
{% endblock content %}