businesses/urls.py
from django.urls import path
from . import views

app_name = "businesses"

urlpatterns = [
    path("<int:pk>/", views.BusinessProfileView.as_view(), name="profile"),
    path(
        "update-business-profile/<int:pk>",
        views.UpdateBusinessProfileView.as_view(),
        name="update-business",
    ),
    path("create/", views.CreateBusinessView.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("menus/", include("menus.urls", namespace="menus")),
    path("users/", include("users.urls", namespace="users")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path("purchases/", include("purchases.urls", namespace="purchases")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from menus import views as menu_views


app_name = "core"

urlpatterns = [
    path("", menu_views.HomeView.as_view(), name="home"),
]

businesses/models.py
from django.db import models
from django.urls import reverse
from core import models as core_models


class Business(core_models.TimeStampedModel):

    """ Business Model Definition """

    STATE_ACT = "ACT"
    STATE_NSW = "NSW"
    STATE_NT = "NT"
    STATE_QLD = "QLD"
    STATE_SA = "SA"
    STATE_TAS = "TAS"
    STATE_VIC = "VIC"
    STATE_WA = "WA"
    STATE_CHOICES = (
        (STATE_ACT, "Australian Capital Territory"),
        (STATE_NSW, "New South Wales"),
        (STATE_NT, "Northern Territory"),
        (STATE_QLD, "Queensland"),
        (STATE_SA, "South Australia"),
        (STATE_TAS, "Tasmania"),
        (STATE_VIC, "Victoria"),
        (STATE_WA, "Western Australia"),
    )

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    state = models.CharField(max_length=50, choices=STATE_CHOICES, default="NSW")
    address = models.CharField(max_length=500, blank=True)
    owner = models.ForeignKey(
        "users.User", related_name="businesses", on_delete=models.CASCADE,
    )
    avatar = models.ImageField(upload_to="business_photo", null=True, blank=True)

    class Meta:
        verbose_name_plural = "businesses"

    def __str__(self):
        return self.name

    def total_rating(self):
        all_reviews = self.reviews.all()
        total_rating = 0

        if all_reviews.count() > 0:
            for review in all_reviews:
                total_rating += review.rating_average()
            return round(total_rating / len(all_reviews), 2)
        return "0"

    total_rating.short_description = "Avg"

    def each_rating(self):
        all_reviews = self.reviews.all()
        ratings = {
            "taste": 0,
            "portion": 0,
            "value": 0,
            "location": 0,
        }

        if all_reviews.count() > 0:
            for review in all_reviews:
                ratings["taste"] += review.get_each_rating()["taste"]
                ratings["portion"] += review.get_each_rating()["portion"]
                ratings["value"] += review.get_each_rating()["value"]
                ratings["location"] += review.get_each_rating()["location"]

            ratings["taste"] = round(ratings["taste"] / len(all_reviews), 2)
            ratings["portion"] = round(ratings["portion"] / len(all_reviews), 2)
            ratings["value"] = round(ratings["value"] / len(all_reviews), 2)
            ratings["location"] = round(ratings["location"] / len(all_reviews), 2)

        return ratings

    def get_absolute_url(self):
        return reverse("businesses:profile", kwargs={"pk": self.pk})

businesses/forms.py
from django import forms
from . import models


class CreateBusinessForm(forms.ModelForm):
    class Meta:
        model = models.Business
        fields = (
            "name",
            "description",
            "state",
            "address",
            "avatar",
        )

    def save(self, *args, **kwargs):
        business = super().save(commit=False)
        return business

businesses/views.py
from django.http import Http404
from django.views.generic import DetailView, UpdateView, FormView
from django.shortcuts import reverse, redirect
from django.contrib import messages
from users import mixins as user_mixins
from . import models, forms


class BusinessProfileView(DetailView):

    """ BusinessProfileView Definition """

    model = models.Business
    context_object_name = "business_obj"


class UpdateBusinessProfileView(UpdateView):

    """ UpdateBusinessProfileView Definition """

    model = models.Business
    template_name = "businesses/update-business-profile.html"
    fields = (
        "name",
        "description",
        "state",
    )
    success_message = "Profile Updated"

    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        business = super().get_object(queryset=queryset)
        if business.owner.pk != self.request.user.pk:
            raise Http404()
        return business

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs = {"placeholder": "Name"}
        form.fields["description"].widget.attrs = {"placeholder": "Description"}
        return form


class CreateBusinessView(user_mixins.LoggedInOnlyView, FormView):

    """ CreateBusinessVies Definition """

    form_class = forms.CreateBusinessForm
    template_name = "businesses/business_create.html"

    def form_valid(self, form):
        business = form.save()
        business.owner = self.request.user
        business.save()
        form.save_m2m()
        messages.success(self.request, "Business Uploaded")
        return redirect(reverse("businesses:profile", kwargs={"pk": business.pk}))

templates/businesses/business_create.html
{% extends "base.html" %}

{% block page_title %}
Create Business
{% endblock page_title %}

{% block content %}

<div class="signup-form m-t-10">
    {% include 'mixins/menu/menu_form.html' with form=form cta="Create business" %}
</div>
{% endblock content %}

templates/businesses/business_detail.html
{% extends "base.html" %}

{% block page_title %}
{{business_obj.name}}'s Profile
{% endblock page_title %}

{% block content %}

<div class="menu-detail">
    <div>
        <span><b>Name: </b>{{business_obj.name}}</span>
    </div>
    <div>
        <span><b>Description: </b>{{business_obj.description}}</span>
    </div>
    <div>
        <span><b>State: </b>{{business_obj.state}}</span>
    </div>
    <div>
        <span><b>Taste: </b>{{business_obj.each_rating.taste}}, <b>Portion: </b>{{business_obj.each_rating.portion}},
            <b>Value: </b>{{business_obj.each_rating.value}}, <b>Location:
            </b>{{business_obj.each_rating.location}} / <b>Avg: </b>{{business_obj.total_rating}}</span>
    </div>
    <div>
        <span><b>Review: </b>{{business_obj.reviews.count}}</span>
        {% for r in business_obj.reviews.all %}
        <div class="review">
            <p class="review-item"><b>{{r.user}} / {{r.created|date:'F-Y'}}:</b></p>
            <p><b>Taste: </b>{{r.get_each_rating.taste}}, <b>Portion: </b>{{r.get_each_rating.portion}},
                <b>Value: </b>{{r.get_each_rating.value}}, <b>Location:
                </b>{{r.get_each_rating.location}}</p>
            <p>{{r.review}}</p>
        </div>
        {% endfor %}
    </div>

    {% if business_obj.owner == user %}
    <div class="m-t-10 m-b-10">
        <a href="{% url 'menus:create' business_obj.pk %}">
            <button>
                Add Menu
            </button>
        </a>
    </div>
    {% endif %}

    {% if business_obj.menus.count > 0 %}
    <h3>{{business_obj.name}}'s currently available menu</h3>
    <div>
        {% for menu in business_obj.menus.all %}
        <div class="w-50per">
            {% include 'mixins/menu_card.html' with menu=menu %}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock content %}

templates/businesses/update-business-profile.html
{% extends "base.html" %}

{% block page_title %}
Update Profile
{% endblock page_title %}

{% block content %}

<div class="signup-form m-t-10 m-b-10">
    {% include 'mixins/auth/auth_form.html' with form=form cta="Update business profile" %}
</div>
{% endblock content %}